name: mask
description: Mobile app for the smart mask bluetooth system
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: 0.7.2
  cupertino_icons: ^0.1.2
  rxdart: ^0.24.0
  charts_flutter: ^0.8.1
  sqflite: ^1.3.0+1
  path_provider: ^1.6.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
